version: '3.4'

services:
  service:
    image: ladislavprix/blog/server
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./data:/app/data